apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
      - {{ include "mongo-express.backend-domain" . }}
    secretName: {{ include "mongo-express.tls-secret-name" . }}
  rules:
  - host: {{ include "mongo-express.backend-domain" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.backendPort }}
